litellm_settings:
  drop_params: true

model_list:

  - model_name: "mistral-medium-latest"
    litellm_params:
      model: "mistral/mistral-medium-latest"
      api_key: "os.environ/MISTRAL_API_KEY"
      api_base: "https://api.mistral.ai/v1"


general_settings:

  pass_through_endpoints:

    - path: "/mistral/v1/ocr"
      target: "https://api.mistral.ai/v1/ocr"
      headers:
        Authorization: "Bearer os.environ/MISTRAL_API_KEY"
        content-type: application/json
        accept: application/json
      forward_headers: true
